apiVersion: v1
kind: Service
metadata:
  name: hellonode
  labels:
    app: hellonode
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hellonode
    tier: hellonode
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellonode
  labels:
    app: hellonode
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hellonode
        tier: hellonode
    spec:
      containers:
      - image: 127.0.0.1:30400/hellonode:latest
        name: hellonode
        ports:
        - containerPort: 8080
          name: hellonode
